### PR TITLE
Solved 6 issues 

### PR DESCRIPTION
**Pull request by RapidCompiler**
Addressed issue #16, by providing a small text file in the repository. This file could help anyone who stumbles upon the repository, understand how this data could be used and what type of analysis could be done on it to help humankind.

Addressed issue #14. I went online and took a look at the press releases published by the MOH. Here, by 'location', the NZ MOH simply refers to the place where the case was reported. I have solved this slight ambiguity by providing a better column title in the main Data Set. I renamed the column to 'Location of Case Report'.

Cracked issue #9. Again, I looked at the press releases and some NZ news websites, and found that the infectious period refers to the period after the initial manifestation of an infectious disease. In this context, the disease takes at most a fortnight to show symptoms. Here, both cases 44 and 51 took international flights, but, before a fortnight (in this context). So, there is no way that the international trips could have led to the infection of those people which is why the MOH has ignored those flights. (You have no idea how long this took for me to solve lol!!)

Solved issue #2. Filled in the missing data points for cases 12 and 13 wherein the contraction in NZ column was left empty. Both the cases did not contract the infections from NZ and I have updated the CSV accordingly.

Addressed issue #13. I have attached a CSV file named Cases_per_Day in the repository. I created the file from data obtained from the NZ MOH. I also have a suggestion. We could include two charts, one of which would show the cases per day and the other the predictions for the forthcoming days. The prediction chart can be plotted from data points and by adding linear regression line which would show the line increasing over the coming days (The dotted line is the prediction). I believe that an exponential regression line must be used for this as the cases do increase exponentially and the linear regression underestimates the number of cases but frankly, I don't know how to do that. If exponential regression is used, then the line (number of cases) would increase much more rapidly (God Forbid.). Please do use an exponential regression line if you know how to do so. **I will not be raising this as an issue for the following reason.**

You might think that the prediction chart might be irrelevant to what your repository has to offer. In such case, please feel free to ignore it.

And finally, I've addressed issue #20, wherein I've changed the format of the dates in both the CSVs to ISO 8601 in order to support easy parsing using python as you mentioned.

So, all in all, I've managed to solve 6 of your issues and I request you to pull in my repository and close the issues accordingly.

Also, I request you to add me as a contributor to this repository so that we can collaborate together. I've also created my own repository and raised an issue as well. Please do check it out and let me know if you're interested in collaborating with me. If you could also solve my issue on my repository, I would highly appreciate it.

Thanks and Regards,
RapidCompiler.

### CODE REVIEW

**Comment by RapidCompiler** [comment]
Did you take a look at this? Shall I merge this to the base branch of our repository?

**Comment by m-kruth** [comment]
Sorry just finished work looking now.

**Comment by m-kruth** [comment]
LGTM, awesome work again! Feel free to merge and close issues.

**Comment by RapidCompiler** [comment]
> Sorry just finished work looking now.

_It's fine!_

**Comment by RapidCompiler** [comment]
> I also have a suggestion. We could include two charts, one of which would show the cases per day and the other the predictions for the forthcoming days. The prediction chart can be plotted from data points and by adding linear regression line which would show the line increasing over the coming days (The dotted line is the prediction). I believe that an exponential regression line must be used for this as the cases do increase exponentially and the linear regression underestimates the number of cases but frankly, I don't know how to do that. If exponential regression is used, then the line (number of cases) would increase much more rapidly (God Forbid.). Please do use an exponential regression line if you know how to do so. I will not be raising this as an issue for the following reason.


This is what I wrote in the description of this pull request. I hope you took a look at the suggestion that I provided for closed issue #13 . The chart drawing part. What do you think of that?

**Comment by m-kruth** [comment]
Hey there, yes I think this is a good idea but is best captured in a Kaggle notebook. It will keep our extrapolations seperate from the dataset which I want to keep as a pure reflection of information provided by the MOH.

**Comment by RapidCompiler** [comment]
Sure. I've another quesiton. What is a kaggle notebook? How do you create and use it? And finally, where do we store it in the repository? I have used kaggle for some research on COVID-19 but have never encountered a notebook before. Please explain.

**Comment by m-kruth** [comment]
Sure, a notebook is just another name for a kernel. There are instructions in this thread: https://www.kaggle.com/getting-started/23393. An example of someone using this dataset to do very basic things can be found here: https://www.kaggle.com/seoshmeo/kernel32f670d839. The guy basically imported the dataset and displayed it with pandas.

**Pull request merged**
